apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "micronaut-api-chart.fullname" . }}
  labels:
    {{- include "micronaut-api-chart.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}   
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
      type: {{ .Values.strategy.updateType }}
      rollingUpdate:
        maxSurge: {{ .Values.strategy.maxSurge }}
        maxUnavailable: {{ .Values.strategy.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "micronaut-api-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "micronaut-api-chart.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      #serviceAccountName: {{ include "micronaut-api-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probeUrl }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.probeUrl }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
