apiVersion: v1
kind: Service
metadata:
  name: {{ include "micronaut-api-chart.fullname" . }}
  labels:
    {{- include "micronaut-api-chart.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}  
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "micronaut-api-chart.selectorLabels" . | nindent 4 }}
